export const actionTypes = {

    // * auth
    SET_TOKEN : "SET_TOKEN",
    REOVE_TOKEN : "REOVE_TOKEN",
    SET_USER_ID : "SET_USER_ID",

    // * profile
    FETCH_USER_PROFILE : "FETCH_USER_PROFILE",

    // * ui
    SET_CHAT_BY_ID: "SET_CHAT_BY_ID",
    ADD_NEW_CONTECT: "ADD_NEW_CONTECT",

    // * messages
    SEND_MESSAGE : "SEND_MESSAGE",
    SET_CHATHISTORY_BOX_OPEN : "SET_CHATHISTORY_BOX_OPEN",
    SET_CHATHISTORY_BOX_CLOSE : "SET_CHATHISTORY_BOX_CLOSE",

    // * notification 
    ADD_NOTIFICATION: "ADD_NOTIFICATION"

}
